第 5 课
========================================================

### 多变量数据
注释：


```{r}
#练习带有分面和颜色的直方图
#https://discussions.youdaxue.com/t/topic/43454/3
ggplot(aes(x = price, fill=cut), data = diamonds) + geom_histogram() +
         facet_wrap(~ color) +
         scale_x_log10() +
         scale_fill_brewer(type = 'qual')

#价格与按切工填色
#https://discussions.youdaxue.com/t/topic/52884
ggplot(aes(x=table,y=price),data=diamonds)+
  geom_point(aes(color=cut))+
  scale_color_brewer(type = 'qual')+
  scale_x_continuous(breaks=seq(50,80,2),lim=c(50,80))

#练习：经过分组
ggplot(aes(x = cut, y = price/carat), data = diamonds) + geom_point(aes(color = color)) + facet_wrap(~ clarity) + scale_color_brewer(type = 'div')

ggplot(aes(x = cut, y = price/carat), data = diamonds) + geom_jitter(aes(color = color)) + facet_wrap(~ clarity) + scale_color_brewer(type = 'div')

#ggplot(aes(x = cut, y = price/carat), data = diamonds) + geom_jitter(aes(color = color), alpha = 1/20) + facet_wrap(~ clarity) + scale_color_brewer(type = 'div')
#jitter真是很实用 alpha在这里就不靠谱了

#gapminder没有做，大致是：https://discussions.youdaxue.com/t/gapminder/43425

#价格与体积和钻石净度
diamonds$volume <- diamonds$x * diamonds$y * diamonds$y
ggplot(aes(x = volume, y = price, color = clarity), data = diamonds) +
geom_point() +
scale_y_log10() +
xlim(0,quantile(diamonds$volume,0.99)) + scale_color_brewer(type = 'div')

#练习：新建友谊的比赛
pf$prop_initiated <- pf$friendships_initiated/pf$friend_count
#ggplot(pf, aes(x=tenure, y=prop_initiated, color=year_joined.bucket)) + geom_line(stat='summary', fun.y=median, na.rm=TRUE)

ggplot(pf, aes(x=tenure, y=prop_initiated, color=year_joined.bucket)) + geom_line(stat='summary', fun.y=median)

ggplot(pf, aes(x=tenure, y=prop_initiated, color=year_joined.bucket)) + geom_line(stat='summary', fun.y=median) + geom_smooth(aes(color = tenure))
#论坛中的多了na.rm测试没有区别，后续研究

#最大组均值
pf.tidy <- subset(pf,prop_initiated != 'NaN')
with(subset(pf.tidy ,year_joined.bucket == '(2012,2014]'),mean(prop_initiated))
#bucket的判断需要使用(]后续研究
#也可以用by来实现
by(pf$prop_initiated, pf$year_joined.bucket, summary)

#经过分组、分面和填色的价格/克拉


```

***

### 年龄标记为彩色的自我感知关注量
注释：

***

### 第三个定性变量
注释：

```{r Third Qualitative Variable}
library(ggplot2)
library(dplyr)
pf <- read.csv('pseudo_facebook.tsv',sep = '\t')
#ggplot(aes(x = gender, y = age), data = subset(pf, !is.na(gender))) + geom_histogram()
ggplot(aes(x = gender, y = age), data = subset(pf, !is.na(gender))) + geom_histogram(stat = "identity")
#定义y=的时候，要在后面geom中增加 stat = ‘identity’，否则会报错。在有的图形的时候（比如上面的换成boxplot就不报错。应该是不同图形对x和y的匹配要求不同。
ggplot(aes(x = gender, y = age), data = subset(pf, !is.na(gender))) + geom_boxplot()

ggplot(aes(x = gender, y = age), data = subset(pf, !is.na(gender))) + geom_boxplot() + stat_summary(fun.y = mean, geom = 'point', shape = 4)
#此句增加了mean的那个x标记

ggplot(aes(x = age, y = friend_count), data = subset(pf, !is.na(gender))) + geom_line(aes(color = gender), stat = 'summary', fun.y = median) 

#使用dplyr,chain funtions together
library(dplyr)
pf.fc_by_age_gender <- pf %>%
  filter(!is.na(gender)) %>%
  group_by(age, gender) %>%
  summarise(mean_friend_count = mean(friend_count), median_friend_count = median(friend_count), n = n()) %>%
  ungroup %>%
  arrange(age)

head(pf.fc_by_age_gender)

#绘制条件小结
ggplot(aes(x = age, y = median_friend_count), data = pf.fc_by_age_gender) + geom_line(aes(color = gender))
```

***

### 绘制条件总结
注释：

```{r Plotting Conditional Summaries}

```

***

### 思考比率
注释：

***

### 又宽又长的格式
注释：

***

### 改变数据
注释：

```{r}
install.packages('reshape2')
library(reshape2)

pf.fc_by_age_gender.wide <- dcast(pf.fc_by_age_gender, age ~ gender, value.var = 'median_friend_count')
#dcast是转换为dataframe，还有acast，转换为martix，后续研究
head(pf.fc_by_age_gender.wide)

ggplot(aes(x = age, y = female/male), data = pf.fc_by_age_gender.wide) + geom_line() + geom_hline(yintercept = 1, alpha = 0.3, linetype = 2)
```

***

### 比率图
注释：

```{r Ratio Plot}

```

***

### 第三个定性变量
注释：

```{r Third Quantitative Variable}
pf$year_joined <- floor(2014 - pf$tenure/365)
```

***

### 减少一个变量
注释：

```{r Cut a Variable}
#2004-2009
#2009-2011
#2011-2012
#2012-2014

summary(pf$year_joined)
table(pf$year_joined)

pf$year_joined.bucket <- cut(pf$year_joined, c(2004, 2009, 2011, 2012, 2014))
#cut的区分是在c中的前后边界。除了第一个之外，每个bucket不包括下边界。就是说2009属于2004-2009，不属于2009-2011

table(pf$year_joined.bucket, useNA = 'ifany')
table(pf$year_joined.bucket)
#useNA是标出NA值，否则默认会去掉

ggplot(aes(x = age, y = friend_count), data = subset(pf, !is.na(gender))) + geom_line(aes(color = gender), stat = 'summary', fun.y = median)

ggplot(aes(x = age, y = friend_count), data = subset(pf, !is.na(gender))) + geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)

ggplot(aes(x = age, y = friend_count), data = subset(pf, !is.na(gender))) + geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = mean) + geom_line(stat = 'summary', fun.y = mean, linetype = 2)
```

***

### 同时绘制
注释：

```{r Plotting it All Together}

```

***

### 绘制总平均值
注释：

```{r Plot the Grand Mean}

```

***

### 交友率
注释：

```{r Friending Rate}
with(subset(pf, tenure >= 1), summary(friend_count/tenure))
```

***

### 开始交友
注释：

平均交友率是什么？

最大交友率是什么？

```{r Friendships Initiated}
ggplot(aes(x = tenure, y = friendships_initiated / tenure), data = subset(pf, tenure >= 1)) + geom_line(aes(color = year_joined.bucket))
#视频中的）有位置错误。图形和课程有点差别，后续研究。
```

***

### 再次访问方差权衡
注释：

```{r Bias-Variance Tradeoff Revisited}

ggplot(aes(x = tenure, y = friendships_initiated / tenure),
       data = subset(pf, tenure >= 1)) +
  geom_line(aes(color = year_joined.bucket),
            stat = 'summary',
            fun.y = mean)

ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

ggplot(aes(x = 30 * round(tenure / 30), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

ggplot(aes(x = 90 * round(tenure / 90), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure), data = subset(pf, tenure > 1)) + geom_line(aes(color = year_joined.bucket), stat = "summary", fun.y = mean)
#理解偏差-方差折衷（Bias-Variance Tradeof）
#http://scott.fortmann-roe.com/docs/BiasVariance.html
#注意：改变分箱的代码将绘图表达式中的 x = tenure 替换为 x = 7 * round(tenure / 7) 等，通过 round 函数中的分母将数值分箱，然后转换回前面带有常量的自然标尺。

ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure), data = subset(pf, tenure > 1)) + geom_smooth(aes(color = year_joined.bucket))

```

***

### Sean 对 NFL 粉丝情绪的研究
注释：

***

###  Yogurt 数据集简介
注释：

***

### 再次访问直方图
注释：

```{r Histograms Revisited}
#设置目录为工作目录
#install.packages("rstudioapi")
library(rstudioapi)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

yo <- read.csv('yogurt.csv')
str(yo)

library(ggplot2)
qplot(data = yo, x = price, fill = I('#F79420'))
```

***

### 购买数量
注释：

```{r Number of Purchases}
summary(yo)
length(unique(yo$price))
table(yo$price)
str(yo)

yo <- transform(yo, all.purchases = strawberry + pina.colada + plain + mixed.berry)
yo$all.purchases
summary(yo$all.purchases)

#qplot(x = all.purchases, data = yo, bindwidth = 1, fill = I('099DD9))

ggplot(aes(x = time, y = price), data = yo) + geom_jitter(alpha = 1/4, shape = 21, fill = I('#F79420'))
```

***

### 一段时期的价格
注释：

```{r Prices over Time}

```

***

### 抽样观察
注释：

***

### 观察家庭的样本

```{r Looking at Sample of Households}
set.seed(4230)
#sample.ids <- sample(levels(yo$id), 16)
#以上是视频中的版本，报错，改为以下解决
#seed的作用是引入相同观察值。sample是选取16个
#set.seed(4230)中的4230是随便选的，没有具体含义.一个特定的种子可以产生一个特定的伪随机序列，这个函数的主要目的，是让你的模拟能够可重复出现，因为很多时候我们需要取随机数，如果不设定种子，这段代码再跑一次的时候，结果就不一样了，如果需要重复出现同样的模拟结果的话，就可以用set.seed()。在调试程序或者做展示的时候，结果的可重复性是很重要的，所以随机数种子也就很有必要。设置种子的目的是确保产生可重复的随机数。如果种子相同，产生的随机数也相同。

str(yo)

sample.ids <- sample(levels(as.factor(yo$id)), 16)

sample.ids

ggplot(aes(x = time, y = price), data = subset(yo, id %in% sample.ids)) + facet_wrap( ~id) + geom_line() + geom_point(aes(size = all.purchases), pch = 1)

#x %in% y 返回一个长度与 x 相同的逻辑（布尔）向量，该向量指出 x 中的每一个条目是否都出现在 y 中。也就是说，对于 x 中的每一个条目，该向量都会检查这一条目是否也出现在 y 中。
```

***

### 交叉分组数据的缺点
注释：
```{r}
#散点图矩阵
library(ggplot2)
install.packages('GGally')
library(GGally)
theme_set(theme_minimal(20))

#set the seed for reproducible results
set.seed(1836)
pf_subset <- pf[, c(2:7)]
names(pf_subset)
ggpairs(pf_subset[sample.int(nrow(pf_subset), 1000),])
#视频中提示axisLabels = 'internal'可以把坐标轴放在中间，没弄好，后续测试
```

***

### 许多变量
注释：

***

### 散点图矩阵
注释：

***

### 更多变量
注释：

***

### 热点图
注释：

```{r}
nci <- read.table("nci.tsv")
colnames(nci) <- c(1:64)
```

```{r}
library(reshape2)
nci.long.samp <- melt(as.matrix(nci[1:200,]))
names(nci.long.samp) <- c("gene", "case", "value")
head(nci.long.samp)

ggplot(aes(y = gene, x = case, fill = value),
  data = nci.long.samp) +
  geom_tile() +
  scale_fill_gradientn(colours = colorRampPalette(c("blue", "red"))(100))
```

***

### 分析三个及三个以上变量
思考：

***

点击 **KnitHTML** 查看你的成果和这节课的 html 页面、
答案和注释！
